// <auto-generated />
using System;
using AcmeManager.Core.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AcmeManager.Core.Storage.Migrations
{
    [DbContext(typeof(AcmeManagerDbContext))]
    [Migration("20260530015026_AddDnsProviders")]
    partial class AddDnsProviders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("AcmeManager.Core.Storage.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("AccountKeyEncrypted")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectoryUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("EabHmacEncrypted")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("EabKeyIdEncrypted")
                        .HasColumnType("BLOB");

                    b.Property<string>("KeyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RegisteredAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("AcmeManager.Core.Storage.Entities.Certificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("NotAfter")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("NotBefore")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RenewalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SansJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StoreReferencesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Thumbprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RenewalId");

                    b.HasIndex("Thumbprint");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("AcmeManager.Core.Storage.Entities.DnsProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PluginId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DnsProviders");
                });

            modelBuilder.Entity("AcmeManager.Core.Storage.Entities.HistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExceptionJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RenewalId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("At");

                    b.HasIndex("RenewalId");

                    b.ToTable("History");
                });

            modelBuilder.Entity("AcmeManager.Core.Storage.Entities.Renewal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstallationsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSuccessAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RenewalWindowDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StoresJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidationJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Renewals");
                });

            modelBuilder.Entity("AcmeManager.Core.Storage.Entities.Secret", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("EncryptedValue")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Secrets");
                });

            modelBuilder.Entity("AcmeManager.Core.Storage.Entities.SettingsValue", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("AcmeManager.Core.Storage.Entities.Certificate", b =>
                {
                    b.HasOne("AcmeManager.Core.Storage.Entities.Renewal", "Renewal")
                        .WithMany()
                        .HasForeignKey("RenewalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Renewal");
                });

            modelBuilder.Entity("AcmeManager.Core.Storage.Entities.HistoryEntry", b =>
                {
                    b.HasOne("AcmeManager.Core.Storage.Entities.Renewal", "Renewal")
                        .WithMany()
                        .HasForeignKey("RenewalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Renewal");
                });

            modelBuilder.Entity("AcmeManager.Core.Storage.Entities.Renewal", b =>
                {
                    b.HasOne("AcmeManager.Core.Storage.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });
#pragma warning restore 612, 618
        }
    }
}
